export default {
	API_LOADING_START: 'API_LOADING_START',
	API_LOADING_END: 'API_LOADING_END',
	SET_DEVICE_HEIGHT: 'SET_DEVICE_HEIGHT',

	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',

	SET_CONTACT: 'SET_CONTACT',
	CLEAR_CONTACT: 'CLEAR_CONTACT',
	LOADING_CONTACT: 'LOADING_CONTACT',

	ADD_NEW_TIMER: 'ADD_NEW_TIMER',
	ADD_ANOTHER_TIMER: 'ADD_ANOTHER_TIMER',
	UPDATE_TIMER: 'UPDATE_TIMER',
	STOP_TIMER: 'STOP_TIMER',
	RESET_TIMER: 'RESET_TIMER',
	RESUME_TIMER: 'SUSPEND_TIMER',

	INCREASE_COUNTER: 'INCREASE_COUNTER',
	RESET_COUNTER: 'RESET_COUNTER',
};
